spring.application.name=github-access-report

# GitHub configuration
github.base-url=https://api.github.com
github.token=${GITHUB_PAT}
github.per-page=100
github.parallelism=20

# Logging
logging.level.root=INFO
logging.level.com.assignment.githubreport=DEBUG

# Actuator
management.endpoints.web.exposure.include=health,info

server.port=${PORT:8080}